name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 2.2.0
homepage: https://jesway.com
repository: https://github.com/Jesway/Flutter-Translate-Gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.11.0
  build: ^2.4.1
  code_builder: ^4.10.0
  dart_casing: ^3.0.1
  dart_style: ^2.3.6
  dart_utils: ^2.0.0
  flutter_translate_annotations: ^2.1.0
  glob: ^2.1.2
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.10